---
name: 'Crosscheck Methods'

on: [push, pull_request]

jobs:
  calc_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
        R: ['4.1.3']
    name: Cross-Check Python, R and Matlab Methods
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pythhon Dependencies
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: Running Python Kgen
        run: |
          cd crosscheck
          python3 gen_python.py
      - name: Set Up R ${{ matrix.R }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Install R dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install curl
          R -e 'install.packages("remotes")'
          R -e 'library(remotes)'
          R -e 'remotes::install_local("r")'
          R -e 'library("Kgen")'
          R -e 'reticulate::install_miniconda()'
          R -e 'reticulate::use_miniconda("r-reticulate")'
          R -e 'reticulate::py_install("pymyami", envname = "r-reticulate", pip=T)'
      - name: Running R Kgen
        run: |
          cd crosscheck
          Rscript gen_r.r
      - name: Setup Matlab
        uses: matlab-actions/setup-matlab@v1
      - name: Run Matlab script
        uses: matlab-actions/run-command@v1
        with:
          command: cd 'crosscheck',addpath("./../matlab/"),gen_matlab
      - name: Comparing Kgen Outputs
        run: |
          cd crosscheck
          python3 -m unittest crosscheck.py
