---
name: 'Crosscheck Methods'

on: [push, pull_request]

jobs:
  calc_python:
    name: Calculating Ks with Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: 'Run Tests'
        run: |
          cd crosscheck
          python3 gen_python.py
  calc_r:
    name: Calculating Ks with R
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: ['4.1.3']
    steps:
      - uses: actions/checkout@v2
      - name: Set Up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Installing Dependencies
        run: |
          cd r
          Rscript setup_r_env.r
      - name: Running Kgen
      - run: |
          cd crosscheck
          Rscript gen_r.r

  crosscheck:
    name: Comparing Outputs
    runs-on: ubuntu-latest
    needs: [calc_python, calc_r]
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: "Set Up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: 'Run Tests'
        run: |
          cd crosscheck
          python3 -m unittest crosscheck.py