---
name: 'Crosscheck Methods'

on: [push, pull_request]

jobs:
  calc_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Calculating Ks with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: Running Kgen
        run: |
          cd crosscheck
          python3 gen_python.py
  calc_r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    strategy:
      matrix:
        R: ['4.1.3']
    name: Calculating Ks with R ${{ matrix.R }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
      - name: Set Up R

      - name: Running Kgen
        run: |
          cd crosscheck
          Rscript gen_r.r
  crosscheck:
    name: Comparing Outputs
    runs-on: ubuntu-latest
    needs: [calc_python, calc_r]
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: "Set Up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: 'Run Tests'
        run: |
          cd crosscheck
          python3 -m unittest crosscheck.py
