---
name: 'Check K values'

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: "Set Up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          cd python
          pwd
          python3 -m pip install -r requirements.txt
      - name: 'Run Tests'
        run: |
          cd python
          python3 -m unittest
