---
name: 'Generate track record'

on: 
  workflow_dispatch
  release:
    types: [released]
  

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    name: Track record
    steps:
      - uses: actions/checkout@v2
      - name: "Set Up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: 'Run generate track record'
        run: |
          python3 ./track_record/generate_track_record.py
          ls -a ./track_record/
