---
name: 'Generate track record'

on:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    name: Track record
    steps:
      - uses: actions/checkout@v2
      - name: "Set Up Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          cd python
          python3 -m pip install -r requirements.txt
      - name: 'Run generate track record'
        run: |
          python3 ./track_record/generate_track_record.py
      - name: 'Recommit information'  
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update of track_record
          file_pattern: './track_record/K_track_record.json ./track_record/recent.png'
        

